export const ACADEMY_VERSION='1.0.0';
const q=(question,options,answer,explanation)=>({question,options,answer,explanation});
const passScore=80;
export const LESSONS=[
{id:'foundations-rgt',concepts:['RUN', 'GROW', 'TRANSFORM'],module:'Fundamentos',title:'Qué es RGT',minutes:5,objective:'Entender cómo RUN, GROW y TRANSFORM organizan la capacidad de ejecución.',body:'RGT separa el trabajo operativo, el crecimiento comercial y la transformación estructural. La intención no es llenar un tablero: es proteger capacidad y convertir prioridades en resultados verificables.',example:'Una incidencia operativa puede ser RUN; una mejora de conversión puede ser GROW; rediseñar una capacidad estructural puede ser TRANSFORM.',check:['Puedo explicar la diferencia entre RUN, GROW y TRANSFORM.','Entiendo que no todo trabajo debe entrar como iniciativa.'],passScore,questions:[q('¿Qué busca proteger RGT?', ['La cantidad de tarjetas','La capacidad de ejecución','El número de reuniones','El volumen de mensajes'],1,'RGT usa foco, capacidad y límites para proteger la ejecución.'),q('¿Cuál es la clasificación correcta?', ['RUN = operación; GROW = crecimiento; TRANSFORM = cambio estructural','RUN = ventas; GROW = soporte; TRANSFORM = reuniones','RUN = IA; GROW = datos; TRANSFORM = tareas'],0,'Los tres pilares representan operación, crecimiento y transformación.')],routes:[]},
{id:'foundations-wip',concepts:['WIP'],module:'Fundamentos',title:'WIP y capacidad',minutes:5,objective:'Aprender por qué limitar el trabajo activo protege la ejecución.',body:'WIP significa trabajo en progreso. En RGT, TRANSFORM tiene un máximo de 2 iniciativas activas. Una tercera no entra aunque parezca importante: primero hay que terminar, cancelar o reordenar con disciplina.',example:'Si ya hay dos iniciativas TRANSFORM activas, una tercera debe esperar o sustituir una existente mediante una decisión explícita.',check:['Sé qué significa WIP.','Sé cuándo una iniciativa TRANSFORM está consumiendo WIP.'],passScore,questions:[q('¿Qué significa WIP?', ['Trabajo en progreso','Trabajo prioritario','Trabajo pendiente','Trabajo planificado'],0,'WIP significa Work In Progress: trabajo actualmente activo.'),q('Hay 2 TRANSFORM activas y llega una tercera. ¿Qué corresponde?', ['Activarla inmediatamente','Ignorar el límite','Terminar/cancelar/reordenar antes de activar otra','Moverla a DONE'],2,'El límite existe para proteger capacidad; no se salta por presión.')],routes:[]},
{id:'foundations-ready-done',concepts:['READY', 'DOD'],module:'Fundamentos',title:'Ready y Done',minutes:7,objective:'Distinguir una iniciativa preparada para ejecutar de una iniciativa realmente terminada.',body:'Ready valida que existe suficiente definición para empezar. Done valida que el resultado fue completado y comprobado. Una tarea no se considera terminada solo porque alguien la movió de columna.',example:'Una iniciativa puede estar Ready porque tiene objetivo, criterio de éxito y dependencias claras; solo pasa a Done cuando la evidencia y el DoD están satisfechos.',check:['Puedo identificar qué falta para que una iniciativa esté Ready.','Entiendo que DoD y evidencia protegen la calidad del cierre.'],passScore,questions:[q('¿Qué responde principalmente Ready?', ['¿Ya terminó?','¿Está suficientemente definida para empezar?','¿Quién la creó?','¿Cuántos comentarios tiene?'],1,'Ready protege la entrada a ejecución: debe existir definición suficiente.'),q('¿Qué hace que Done sea confiable?', ['Mover la tarjeta','Que pase el DoD y exista evidencia cuando corresponda','Cambiar el título','Que tenga muchos comentarios'],1,'Done representa un resultado terminado y comprobado, no solo un cambio visual.')],routes:[]},
{id:'weekly-mustwin',concepts:['MUST_WIN'],module:'Operación semanal',title:'Los 3 Must-Win',minutes:6,objective:'Aprender a convertir la semana en tres batallas concretas.',body:'Cada sprint tiene exactamente tres Must-Win: uno RUN, uno GROW y uno TRANSFORM. Son compromisos de foco, no una lista de todo lo que existe en el tablero.',example:'Si una semana tiene diez prioridades, los Must-Win obligan a identificar la batalla concreta que representa RUN, GROW y TRANSFORM.',check:['Tengo claro qué hace que algo sea Must-Win.','Puedo identificar uno por cada pilar.'],passScore,questions:[q('¿Cuántos Must-Win debe tener el sprint?', ['Uno','Tres: uno por pilar','Cinco','Los que quepan'],1,'El modelo define exactamente tres: RUN, GROW y TRANSFORM.'),q('¿Qué describe mejor un Must-Win?', ['Todo el trabajo del tablero','Un compromiso concreto de foco','Una alerta técnica','Una tarea cualquiera'],1,'Es una batalla concreta de la semana, no un inventario de pendientes.')],routes:[]},
{id:'weekly-deepwork',concepts:['DEEP_WORK'],module:'Operación semanal',title:'Deep Work',minutes:6,objective:'Usar bloques protegidos para trabajo que necesita concentración.',body:'Deep Work es un timebox de 120 minutos. Prioriza TRANSFORM y GROW y excluye el trabajo reactivo RUN. El objetivo es proteger ejecución estructural, no simplemente ocupar el calendario.',example:'Un bloque puede dedicarse a completar una parte concreta de una iniciativa GROW y terminar con un resultado verificable.',check:['Sé qué iniciativas son candidatas a Deep Work.','Entiendo por qué RUN no debe llenar un bloque de concentración.'],passScore,questions:[q('¿Cuánto dura un bloque Deep Work?', ['30 minutos','60 minutos','120 minutos','Todo el día'],2,'El estándar RGT definido para Deep Work es un timebox de 120 minutos.'),q('¿Qué pilares prioriza?', ['Solo RUN','GROW y TRANSFORM','Solo TRANSFORM','Todos por igual'],1,'Deep Work protege trabajo que necesita concentración, priorizando GROW y TRANSFORM.')],routes:[]},
{id:'weekly-review',concepts:['WEEKLY_REVIEW', 'CARRY_OVER'],module:'Operación semanal',title:'Weekly Review y carry-over',minutes:7,objective:'Cerrar la semana sin esconder trabajo inconcluso.',body:'La Weekly Review revisa resultados, bloqueos y trabajo que continúa. El carry-over conserva la misma iniciativa y hace visible que la ejecución sigue abierta.',example:'Una iniciativa incompleta no se duplica para la siguiente semana: permanece visible como carry-over y se revisa su situación.',check:['Sé qué revisar el viernes.','Entiendo que carry-over no significa duplicar una iniciativa.'],passScore,questions:[q('¿Qué debe revisar la Weekly Review?', ['Solo tareas cerradas','Resultados, bloqueos y trabajo que continúa','Solo reuniones','Solo la IA'],1,'La revisión hace visible el estado real de la ejecución.'),q('¿Qué significa carry-over?', ['Duplicar una iniciativa','Eliminar una iniciativa','Continuar explícitamente la misma iniciativa','Marcarla como Done'],2,'Carry-over conserva la iniciativa y deja visible que sigue abierta.')],routes:[]},
{id:'advanced-health',concepts:['EXECUTION_HEALTH'],module:'Avanzado',title:'Execution Health',minutes:7,objective:'Leer la salud de ejecución sin confundirla con un pronóstico comercial.',body:'Execution Health observa capacidad, flujo, entrega y foco. Es una lectura operativa determinística. No sustituye el análisis comercial de RevNavigator.',example:'Una mala salud por exceso de WIP indica una condición operativa que debe investigarse; no demuestra por sí sola una caída comercial.',check:['Puedo explicar qué mide Execution Health.','Sé distinguir salud de ejecución de desempeño comercial.'],passScore,questions:[q('¿Qué tipo de lectura es Execution Health?', ['Forecast comercial','Lectura operativa determinística','Opinión de IA','Encuesta de satisfacción'],1,'Execution Health resume condiciones de ejecución observables.'),q('¿Qué NO debe concluirse automáticamente?', ['Que existe una condición de capacidad','Que hay fricción operativa','Que existe un forecast comercial negativo','Que hay una señal de foco'],2,'Salud de ejecución y desempeño comercial son dimensiones distintas.')],routes:[]},
{id:'advanced-discipline',concepts:['DISCIPLINE', 'WIP', 'READY', 'DOD'],module:'Avanzado',title:'Disciplina de ejecución',minutes:8,objective:'Usar RGT como sistema operativo y no como lista de pendientes.',body:'La disciplina aparece cuando el sistema limita WIP, exige Ready, protege DoD, hace visibles bloqueos y fuerza una revisión semanal. El objetivo es reducir trabajo abierto sin control.',example:'Una semana caótica mejora cuando se limita el trabajo activo, se explicitan Must-Win y se decide qué continúa, qué termina y qué se bloquea.',check:['Sé detectar señales de sobrecarga.','Puedo convertir una semana caótica en prioridades explícitas.'],passScore,questions:[q('¿Qué combinación representa disciplina RGT?', ['Más trabajo abierto','WIP + Ready + DoD + revisión semanal','Más reuniones','Más automatizaciones sin validación'],1,'La disciplina nace de límites, definición, evidencia y revisión.'),q('¿Qué debe pasar con trabajo abierto sin control?', ['Ocultarlo','Duplicarlo','Hacerlo visible y tomar una decisión explícita','Ignorarlo'],2,'RGT busca reducir trabajo abierto sin control mediante decisiones explícitas.')],routes:[]}
];
export const CONTEXT={
 dashboard:{title:'Command Center',what:'Es la vista de control diario. Resume dónde poner atención y qué requiere acción.',do:'Revisa primero atención, Must-Win y siguiente acción. No empieces por abrir todas las tarjetas.',correct:'Puedes explicar cuáles son tus tres focos y qué bloqueos requieren tratamiento.'},
 board:{title:'RGT Board',what:'Es el flujo de iniciativas entre RUN, GROW y TRANSFORM.',do:'Mantén las iniciativas actualizadas y respeta WIP. Antes de iniciar, valida Ready.',correct:'El trabajo activo es ejecutable y TRANSFORM no supera su capacidad.'},
 planning:{title:'Planning Semanal',what:'Es donde conviertes la capacidad de la semana en tres Must-Win.',do:'Define exactamente un Must-Win por pilar.',correct:'Puedes decir qué batalla representa cada pilar y qué resultado busca.'},
 'deep-work':{title:'Deep Work',what:'Protege bloques de concentración para trabajo GROW y TRANSFORM.',do:'Elige una iniciativa candidata y ejecuta un bloque de 120 minutos sin mezclar trabajo reactivo.',correct:'El bloque tiene una iniciativa concreta y termina con un resultado verificable.'},
 review:{title:'Weekly Review',what:'Cierra la semana, revisa resultados y hace visible el trabajo que continúa.',do:'Revisa Must-Win, DoD, bloqueos y carry-over.',correct:'Ningún trabajo inconcluso desaparece; queda explícitamente continuado o cerrado.'},
 performance:{title:'Performance',what:'Mide cómo se ejecutó el sistema durante un periodo.',do:'Lee primero los hechos determinísticos y después usa la narrativa IA como explicación.',correct:'Puedes distinguir hechos, fricciones y narrativa de IA.'},
 'execution-health':{title:'Execution Health',what:'Resume la salud operativa de capacidad, flujo, entrega y foco.',do:'Investiga la dimensión que requiere atención antes de abrir más trabajo.',correct:'La salud explica una condición operativa; no es un forecast comercial.'},
 history:{title:'Historial',what:'Es el registro cronológico de cambios de estado, bloqueos, sesiones y acciones confirmadas.',do:'Úsalo para reconstruir qué pasó y por qué antes de la Weekly Review.',correct:'Puedes rastrear cualquier cambio de una iniciativa hasta su acción registrada.'},
 alerts:{title:'Alertas',what:'Son señales determinísticas que piden atención: WIP, bloqueos, DoD, Sprint vencido y Must-Win incompletos.',do:'Atiende primero las BLOCKER; una alerta no sustituye tu criterio.',correct:'Cada alerta activa tiene una decisión o un desbloqueo asignado.'},
 backup:{title:'Backup & Datos',what:'Exporta y restaura el estado completo de RGT con validación previa.',do:'Exporta antes de cambios importantes; al restaurar se descarga un backup de rollback automático.',correct:'Tienes un JSON reciente guardado fuera del navegador.'},
 'ai-settings':{title:'IA / Cohere',what:'Configura el proveedor de IA que interpreta y propone. No calcula ni escribe datos por sí mismo.',do:'Guarda tu key, prueba la conexión y recuerda que en el navegador una API key no es un secreto.',correct:'La conexión está probada y sabes qué datos se envían a Cohere.'},
 academy:{title:'RGT Academy',what:'Es la ruta de aprendizaje del método dentro de la herramienta.',do:'Sigue Fundamentos → Operación semanal → Avanzado y completa las comprobaciones de cada lección.',correct:'Puedes explicar y aplicar WIP, Ready, Done, Must-Win y Deep Work sin consultar la lección.'},
 assistant:{title:'RGT Assistant',what:'Permite consultar el estado de RGT en lenguaje natural.',do:'Pregunta sobre datos existentes y verifica la fuente de la respuesta.',correct:'La respuesta está sustentada en datos RGT y no crea hechos.'}
};
