import {requestRender} from "../core/events.js";
import {state} from "../core/state.js";
import {askRGT} from "../ai/rgtAssistant.js";
import {isAIConfigured} from "../ai/aiConfig.js";
import {prepareAction,executeConfirmedAction,ACTION_TYPES} from "../ai/actionEngine.js";
const prompts=["¿Qué tengo pendiente hoy?","¿Cuáles son mis 3 Must-Win?","¿Qué está bloqueado?","¿Qué puedo hacer durante Deep Work?","¿Dónde se está acumulando trabajo?","Inicia Deep Work en la iniciativa estratégica disponible"];
let pending=null;
export function assistant(){return `<div class="head" data-rgt-target="assistant-header"><div><div class="eyebrow">Consulta + acciones controladas</div><h1>RGT Assistant</h1><div class="sub">RGT proporciona los hechos y valida las acciones. La IA nunca modifica datos sin tu confirmación explícita.</div></div><span class="badge muted">CONFIRMATION REQUIRED</span></div>
<section class="panel assistant-panel"><div class="assistant-prompts">${prompts.map((p,i)=>`<button class="btn ${i===0?"primary":""}" data-assistant-prompt="${esc(p)}">${esc(p)}</button>`).join("")}</div>
<div class="assistant-input"><textarea id="assistant-question" rows="3" placeholder="Ej. Inicia la iniciativa T123 y luego explícame qué validaste."></textarea><button class="btn dark" id="assistant-ask">Consultar</button></div><div id="assistant-result"></div></section>
<section class="panel" style="margin-top:14px"><h2>Cómo funciona una acción</h2><div class="grid3"><div><b>1. Proponer</b><p class="sub">Cohere interpreta tu solicitud y prepara una acción estructurada.</p></div><div><b>2. Confirmar</b><p class="sub">Tú decides si quieres ejecutarla. Nada ocurre antes de confirmar.</p></div><div><b>3. Validar y ejecutar</b><p class="sub">RGT aplica Ready, DoD, WIP y registra la mutación en Activity Log.</p></div></div></section>`}
export function bindAssistant(){document.querySelectorAll("[data-assistant-prompt]").forEach(b=>b.addEventListener("click",()=>{document.querySelector("#assistant-question").value=b.dataset.assistantPrompt;ask();}));document.querySelector("#assistant-ask")?.addEventListener("click",ask);}
async function ask(){const box=document.querySelector("#assistant-result"),q=document.querySelector("#assistant-question")?.value.trim();if(!q)return; if(!isAIConfigured()){box.innerHTML=`<div class="assistant-error">Configura primero tu API de Cohere en <b>IA / Cohere</b>.</div>`;return;}box.innerHTML=`<div class="assistant-loading">Consultando RGT y preparando la respuesta…</div>`;try{const r=await askRGT(q,{snapshot:state.get()});pending=r.proposal;renderResult(r,box)}catch(e){box.innerHTML=`<div class="assistant-error">${esc(e.message)}</div>`}}
function renderResult(r,box){const p=r.proposal||{action:ACTION_TYPES.NONE};const prep=prepareAction(p,state.get());const proposal=p.action!==ACTION_TYPES.NONE&&prep.allowed;box.innerHTML=`<div class="assistant-answer"><div class="assistant-answer-head"><span class="badge ${proposal?"warn":"muted"}">${proposal?"ACCIÓN PROPUESTA":"CONSULTA"}</span></div><p>${esc(r.message)}</p>${r.facts?.length?`<h3>Hechos</h3><ul>${r.facts.map(x=>`<li>${esc(x)}</li>`).join("")}</ul>`:""}${r.actions?.length?`<h3>Próximos pasos</h3><ul>${r.actions.map(x=>`<li>${esc(x)}</li>`).join("")}</ul>`:""}${proposal?`<div class="assistant-proposal"><b>${esc(prep.summary)}</b><p>RGT todavía no ha ejecutado nada. Al confirmar, volverá a validar los gates con el estado actual.</p><div class="modal-actions"><button class="btn primary" id="assistant-confirm">Confirmar y ejecutar</button><button class="btn" id="assistant-reject">Cancelar</button></div></div>`:""}<small>Fuente determinística: ${esc(r.source_tool)}</small></div>`;document.querySelector("#assistant-confirm")?.addEventListener("click",confirmAction);document.querySelector("#assistant-reject")?.addEventListener("click",()=>{pending=null;document.querySelector("#assistant-result")?.insertAdjacentHTML("beforeend",`<div class="assistant-loading">Acción descartada. No se modificaron datos.</div>`);});}
async function confirmAction(){if(!pending)return;const result=document.querySelector("#assistant-result");const snapshot=state.get();const prep=prepareAction(pending,snapshot);if(!prep.allowed){result.insertAdjacentHTML("beforeend",`<div class="assistant-error">La validación actual bloqueó la acción: ${esc(prep.errors.join(" "))}</div>`);pending=null;return;}if(!window.confirm(`¿Confirmas esta acción?\n\n${prep.summary}`))return;try{const out=await executeConfirmedAction(pending,state.get());pending=null;state.set(await (await import("../db/indexedDB.js")).db.snapshot());requestRender();setTimeout(()=>{const el=document.querySelector("#assistant-result");if(el)el.innerHTML=`<div class="assistant-answer"><p><b>Acción ejecutada.</b> ${esc(out.message)}</p><small>Registrada en Activity Log.</small></div>`},0)}catch(e){result.insertAdjacentHTML("beforeend",`<div class="assistant-error">No se ejecutó: ${esc(e.message)}</div>`);pending=null;}}
function esc(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
