import {progress} from '../learning/index.js';
import {db} from '../db/indexedDB.js';
import {requestRender} from '../core/events.js';
import {state} from '../core/state.js';
import {buildBackup,validateBackup,formatBackupSummary} from '../engines/backupEngine.js';
export function backup(){return `<div class=head><div><div class=eyebrow>Continuidad operativa</div><h1>Backup & Datos</h1><div class=sub>Exporta o restaura el estado completo de RGT. No modifica el motor comercial de RevNavigator.</div></div></div>
<section class=grid2><article class=panel><h2>Exportar backup</h2><p class=mini>Genera un JSON portable con Sprints, iniciativas, DoD, evidencia, Deep Work, reviews e historial.</p><div class=callout><b>Antes de cambios importantes:</b> exporta un backup y conserva el archivo fuera del navegador.</div><div class=modal-actions><button class="btn primary" id="exportBackup">Descargar backup JSON</button></div></article>
<article class=panel><h2>Restaurar backup</h2><p class=mini>La restauración reemplaza los datos locales actuales. El archivo se valida antes de escribirlo.</p><label class="backup-drop"><input id="importBackup" type="file" accept="application/json,.json"><span>Seleccionar archivo JSON</span></label><div id="backupResult" class="mini">Ningún archivo seleccionado.</div><div class=modal-actions><button class="btn dark" id="restoreBackup" disabled>Restaurar datos</button></div></article></section>
<section class="panel" style="margin-top:14px"><div class=section-head><h2>Estado local</h2><span class=status>IndexedDB</span></div><p class=mini>Datos actuales: ${formatBackupSummary({data:state.get()})}</p><p class=mini>El backup no contiene credenciales ni secretos; RGT sigue funcionando sin backend.</p></section>`}
export function bindBackup(){
 const d=()=>state.get(), input=document.querySelector('#importBackup'), result=document.querySelector('#backupResult'), restore=document.querySelector('#restoreBackup');
 document.querySelector('#exportBackup')?.addEventListener('click',()=>{download(buildBackup(d(),{source:'RGT Execution OS'}),`rgt-execution-os-backup-${new Date().toISOString().slice(0,10)}.json`)});
 input?.addEventListener('change',async()=>{const file=input.files?.[0];if(!file)return;try{const payload=JSON.parse(await file.text());const check=validateBackup(payload);window.__rgtPendingBackup=check.valid?payload:null;restore.disabled=!check.valid;result.className=`mini ${check.valid?'backup-valid':'backup-invalid'}`;result.textContent=check.valid?`✓ Backup válido · ${formatBackupSummary(payload)}`:`✕ ${check.errors.join(' ')}`}catch(e){window.__rgtPendingBackup=null;restore.disabled=true;result.className='mini backup-invalid';result.textContent='✕ JSON inválido o ilegible.'}});
 restore?.addEventListener('click',async()=>{const payload=window.__rgtPendingBackup;if(!payload)return;if(!confirm('Esto reemplazará todos los datos locales actuales. Antes se descargará automáticamente un backup de rollback. ¿Continuar?'))return;const live=await db.snapshot();download(buildBackup(live,{source:'pre-restore-rollback'}),`rgt-rollback-before-restore-${Date.now()}.json`);try{await db.replaceSnapshot(payload.data)}catch(e){result.className='mini backup-invalid';result.textContent='✕ La restauración falló y no se modificó ningún dato: '+e.message;return}const snapshot=await db.snapshot();await db.put('activity',{id:`A${Date.now()}`,timestamp:new Date().toISOString(),entity_id:'SYSTEM',action:'BACKUP_RESTORED',detail:'Restauración de backup validado'});state.set(snapshot);await progress.load();window.__rgtPendingBackup=null;requestRender();alert('Backup restaurado correctamente.');});
}
function download(payload,name){const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
