import {homeBrief} from "./homeBrief.js";
import {getActiveSprint,calculatePacing} from "../engines/sprintEngine.js";
import {getMustWinIds} from "../engines/mustWinEngine.js";
export function dashboard(d){
 const s=getActiveSprint(d.sprints)||d.sprints[0]||{},localP=calculatePacing(s,new Date()),p=d.externalPacing?{...localP,target:d.externalPacing.target,actual:d.externalPacing.actual,pacing:d.externalPacing.target?d.externalPacing.actual/d.externalPacing.target:0,requiredDaily:d.externalPacing.remainingDays>0?Math.max(0,(d.externalPacing.target-d.externalPacing.actual)/d.externalPacing.remainingDays):0,remainingDays:d.externalPacing.remainingDays??localP.remainingDays}:localP,ids=getMustWinIds(s,d.initiatives),i=d.initiatives,w=i.filter(x=>x.pillar==="TRANSFORM"&&["IN_PROGRESS","BLOCKED"].includes(x.status)).length,b=i.filter(x=>x.status==="BLOCKED").length,dd=d.checklist.filter(x=>!x.is_completed).length;
 return `<div class=head><div><div class=eyebrow>Centro de Control</div><h1>Command Center</h1><div class=sub>La operación debe decirte dónde poner atención, no solo mostrar información.</div></div><div><button class="btn dark" data-go="deep-work">◉ Iniciar Deep Work</button> <button class="btn primary" data-go="planning">Planning Semanal</button></div></div>
 <div class=kpis><div class=kpi><small>Meta mensual</small><strong>${money(p.target)}</strong></div><div class="kpi good"><small>Acumulado</small><strong>${money(p.actual)}</strong></div><div class="kpi ${p.pacing<.8?"warn":"good"}"><small>Pacing</small><strong>${pc(p.pacing)}</strong></div><div class=kpi><small>Venta diaria requerida</small><strong>${money(p.requiredDaily)}</strong></div><div class=kpi><small>CR Actual</small><strong>${pc(s.actual_cr)}</strong></div><div class=kpi><small>AOV Actual</small><strong>${money(s.actual_aov)}</strong></div></div>
 ${homeBrief(d)}
 <div class=grid2><section class=panel><div class=section-head><h2>Must-Win Battles</h2><span class=status>${ids.length}/3 definidas</span></div><div class=battles>${["RUN","GROW","TRANSFORM"].map(pillar=>{let x=ids.map(id=>i.find(a=>a.id===id)).find(a=>a?.pillar===pillar);return `<div class="battle ${pillar.toLowerCase()}"><b>${pillar}</b><h3>${esc(x?.title||"Sin Must-Win")}</h3><p>${esc(x?.success_criteria||"Configura el Battle en Planning Semanal.")}</p></div>`}).join("")}</div></section>
 <section class=panel><h2>Attention Required</h2><div class=row><span>WIP Transform</span><b>${w}/2</b></div><div class=row><span>Bloqueadas</span><b>${b}</b></div><div class=row><span>DoD pendientes</span><b>${dd}</b></div><div class=row><span>Días restantes</span><b>${p.remainingDays}</b></div></section></div>
 <div class=grid2 style="margin-top:14px"><section class=panel><h2>Estado RGT</h2>${["RUN","GROW","TRANSFORM"].map(pillar=>`<div class=row><span>${pillar}</span><b>${i.filter(x=>x.pillar===pillar&&x.status==="IN_PROGRESS").length} active · ${i.filter(x=>x.pillar===pillar&&x.status==="BLOCKED").length} blocked</b></div>`).join("")}</section>
 <section class=panel><h2>Sprint ${s.status==="ACTIVE"?"ACTIVE":"CLOSED"} · Semana ${s.week_number||"—"}</h2><div class=row><span>Periodo</span><b>${s.start_date||"—"} → ${s.end_date||"—"}</b></div><div class=row><span>Meta Sprint</span><b>${money(s.target_revenue)}</b></div><div class=row><span>Pacing Sprint</span><b>${pc(s.target_revenue?s.actual_revenue/s.target_revenue:0)}</b></div></section></div>`;
}
function esc(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]||c))}
function money(n){return "$"+Number(n||0).toLocaleString("es-MX",{maximumFractionDigits:0})}
function pc(n){return (Number(n||0)*100).toFixed(1)+"%"}
