import {loadAIConfig,isAIConfigured} from "../ai/aiConfig.js";
import {draftInitiative} from "../ai/initiativeCopilot.js";
import {openCreateInitiative} from "./initiativeDetail.js";
import {state} from "../core/state.js";

const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
export function openInitiativeCopilot(){
 document.querySelector("#ai-copilot-modal")?.remove();
 document.body.insertAdjacentHTML("beforeend",`<div class="modal-backdrop" id="ai-copilot-modal"><div class="modal ai-copilot-modal"><div class="modal-head"><div><div class="eyebrow">COHERE · DRAFT</div><h2>Initiative Copilot</h2><p class="muted">Describe el trabajo en lenguaje natural. RGT validará todo antes de guardar.</p></div><button class="icon-btn" id="ai-copilot-close">×</button></div><section class="copilot-body"><label class="copilot-label">¿Qué necesitas hacer?</label><textarea id="ai-copilot-request" rows="5" placeholder="Ej. Revisar el checkout porque estamos teniendo problemas con pagos y necesitamos encontrar dónde falla."></textarea><div class="copilot-note">La IA propone pilar, objetivo, criterio de éxito, prioridad y estimación. No crea ni modifica ninguna iniciativa.</div><div class="modal-actions"><button class="btn" id="ai-copilot-cancel">Cancelar</button><button class="btn primary" id="ai-copilot-generate">Generar borrador</button></div><div id="ai-copilot-result"></div></section></div></div>`);
 const close=()=>document.querySelector("#ai-copilot-modal")?.remove();document.querySelector("#ai-copilot-close").onclick=close;document.querySelector("#ai-copilot-cancel").onclick=close;
 document.querySelector("#ai-copilot-generate").onclick=async()=>{const req=document.querySelector("#ai-copilot-request").value.trim(),out=document.querySelector("#ai-copilot-result"),btn=document.querySelector("#ai-copilot-generate");if(!isAIConfigured())return out.innerHTML='<div class="copilot-error">Configura Cohere primero en <b>IA / Cohere</b>.</div>';if(!req)return out.innerHTML='<div class="copilot-error">Describe lo que necesitas hacer.</div>';btn.disabled=true;btn.textContent="Generando…";out.innerHTML='<div class="copilot-loading">Analizando la solicitud y preparando borrador…</div>';try{const draft=await draftInitiative(req,state.get(),loadAIConfig());renderDraft(out,draft,close)}catch(e){out.innerHTML=`<div class="copilot-error">${esc(e.message)}</div>`}finally{btn.disabled=false;btn.textContent="Generar borrador"}};
}
function renderDraft(out,d,close){out.innerHTML=`<div class="copilot-result"><div class="copilot-result-head"><div><small class="eyebrow">BORRADOR</small><h3>${esc(d.title)}</h3></div><span class="badge muted">${esc(d.pillar)}</span></div><div class="copilot-grid"><div><b>Descripción</b><p>${esc(d.description)}</p></div><div><b>Objetivo</b><p>${esc(d.objective)}</p></div><div><b>Criterio de éxito</b><p>${esc(d.success_criteria)}</p></div><div><b>Responsable</b><p>${esc(d.owner)||"Sin definir"}</p></div><div><b>Prioridad</b><p>${esc(d.priority)}</p></div><div><b>Estimación</b><p>${esc(d.estimated_minutes)} min · esfuerzo ${esc(d.effort)}</p></div><div><b>Dependencias</b><p>${esc(d.dependencies)}</p></div><div><b>Confianza</b><p>${Math.round(d.confidence*100)}%</p></div></div>${d.clarifying_questions?.length?`<div class="copilot-questions"><b>Preguntas para mejorar el borrador</b><ul>${d.clarifying_questions.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div>`:""}<div class="copilot-warning">Este borrador no se ha guardado. Al usarlo solo se rellenará el formulario de creación; todavía tendrás que revisar y confirmar la iniciativa y su DoD.</div><div class="modal-actions"><button class="btn" id="ai-copilot-back">Seguir editando</button><button class="btn primary" id="ai-copilot-use">Usar borrador en nueva iniciativa</button></div></div>`;document.querySelector("#ai-copilot-back").onclick=()=>out.innerHTML="";document.querySelector("#ai-copilot-use").onclick=()=>{close();openCreateInitiative({...d,dod:"Resultado validado y documentado"})};}
