import {db} from "../db/indexedDB.js";
import {state} from "../core/state.js";
import {validateStatusChange} from "../engines/wipEngine.js";
import {canStartTaskReady} from "../engines/readyEngine.js";
import {canCompleteTask} from "../engines/dodEngine.js";

const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const label=s=>String(s).replaceAll("_"," ");

export function openCreateInitiative(prefill={}){
 const old=document.querySelector("#initiative-modal");if(old)old.remove();
 document.body.insertAdjacentHTML("beforeend",`<div class="modal-backdrop" id="initiative-modal"><div class="modal"><div class="modal-head"><div><div class="eyebrow">Nueva iniciativa</div><h2>Definition of Ready</h2></div><button class="icon-btn" id="close-modal">×</button></div><section style="padding:20px"><div class="formgrid"><div class="field full"><label>Nombre</label><input id="c-title" placeholder="Ej. Automatizar QA de checkout" value="${esc(prefill.title||"")}"></div><div class="field"><label>Pilar</label><select id="c-pillar"><option ${prefill.pillar==="RUN"?"selected":""}>RUN</option><option ${prefill.pillar==="GROW"?"selected":""}>GROW</option><option ${prefill.pillar==="TRANSFORM"?"selected":""}>TRANSFORM</option></select></div><div class="field"><label>Responsable</label><input id="c-owner" value="${esc(prefill.owner||"")}"></div><div class="field full"><label>Descripción / problema</label><textarea id="c-description" rows="2">${esc(prefill.description||"")}</textarea></div><div class="field"><label>Objetivo</label><textarea id="c-objective" rows="2">${esc(prefill.objective||"")}</textarea></div><div class="field"><label>Criterio de éxito</label><textarea id="c-success" rows="2">${esc(prefill.success_criteria||"")}</textarea></div><div class="field"><label>Dependencias</label><input id="c-dependencies" placeholder="Ninguna" value="${esc(prefill.dependencies||"")}"></div><div class="field"><label>Prioridad</label><select id="c-priority"><option ${prefill.priority==="Alta"?"selected":""}>Alta</option><option ${!prefill.priority||prefill.priority==="Media"?"selected":""}>Media</option><option ${prefill.priority==="Baja"?"selected":""}>Baja</option></select></div><div class="field full"><label>Primer requisito DoD</label><input id="c-dod" placeholder="Ej. Resultado validado con evidencia" value="${esc(prefill.dod||"")}"></div></div><div class="modal-actions"><button class="btn" id="close-create">Cancelar</button><button class="btn primary" id="create-task">Crear en BACKLOG</button></div></section></div></div>`);
 const close=()=>document.querySelector("#initiative-modal")?.remove();document.querySelector("#close-modal").onclick=close;document.querySelector("#close-create").onclick=close;document.querySelector("#create-task").onclick=async()=>{const v=id=>document.querySelector(id).value.trim();const task={id:`${v("#c-pillar")[0]}${Date.now().toString().slice(-5)}`,title:v("#c-title"),description:v("#c-description"),pillar:v("#c-pillar"),status:"BACKLOG",owner:v("#c-owner"),priority:v("#c-priority"),is_must_win:false,objective:v("#c-objective"),success_criteria:v("#c-success"),dependencies:v("#c-dependencies")||"Ninguna",evidence_required:false,created_at:new Date().toISOString()};const issues=canStartTaskReady(task,[{id:"new",task_id:task.id,category:"DOD",description:v("#c-dod"),required:true,is_completed:false}]);if(!task.title||!task.description||!task.owner||!task.objective||!task.success_criteria||!v("#c-dod"))return toast("Completa los campos esenciales y el primer requisito DoD.","error");await db.put("initiatives",task);await db.put("checklist",{id:crypto.randomUUID(),task_id:task.id,category:"DOD",description:v("#c-dod"),required:true,is_completed:false});await log(task.id,"INITIATIVE_CREATED","Creada en BACKLOG");state.set(await db.snapshot());close();window.dispatchEvent(new Event("rgt:render"));toast("Iniciativa creada en BACKLOG.","success")};
}

export function openInitiativeDetail(id){
  const d=state.get(),task=d.initiatives.find(x=>x.id===id); if(!task)return;
  const old=document.querySelector("#initiative-modal"); if(old)old.remove();
  document.body.insertAdjacentHTML("beforeend",modal(task,d));
  bindModal(task.id);
}
function modal(t,d){
 const dod=d.checklist.filter(x=>x.task_id===t.id&&x.category==="DOD"),ev=d.evidence.filter(x=>x.task_id===t.id),ready=canStartTaskReady(t,d.checklist),done=canCompleteTask(t,d.checklist,d.evidence);
 return `<div class="modal-backdrop" id="initiative-modal"><div class="modal"><div class="modal-head"><div><div class="eyebrow">${esc(t.pillar)} · ${esc(t.id)}</div><h2>${esc(t.title)}</h2><span class="status ${t.status.toLowerCase().replaceAll("_","-" )}">${label(t.status)}</span></div><button class="icon-btn" id="close-modal">×</button></div>
 <div class="modal-grid"><section><div class="tabs"><button class="tab active">Iniciativa</button><span class="tab-note">Gatekeeper integrado al detalle</span></div>
 <div class="formgrid"><div class="field full"><label>Nombre</label><input id="f-title" value="${esc(t.title)}"></div><div class="field"><label>Pilar</label><select id="f-pillar"><option ${t.pillar==="RUN"?"selected":""}>RUN</option><option ${t.pillar==="GROW"?"selected":""}>GROW</option><option ${t.pillar==="TRANSFORM"?"selected":""}>TRANSFORM</option></select></div><div class="field"><label>Responsable</label><input id="f-owner" value="${esc(t.owner)}"></div><div class="field full"><label>Descripción / problema</label><textarea id="f-description" rows="2">${esc(t.description)}</textarea></div><div class="field"><label>Objetivo</label><textarea id="f-objective" rows="2">${esc(t.objective)}</textarea></div><div class="field"><label>Criterio de éxito</label><textarea id="f-success" rows="2">${esc(t.success_criteria)}</textarea></div><div class="field"><label>Dependencias</label><input id="f-dependencies" value="${esc(t.dependencies)}"></div><div class="field"><label>Prioridad</label><select id="f-priority"><option ${t.priority==="Alta"?"selected":""}>Alta</option><option ${t.priority==="Media"?"selected":""}>Media</option><option ${t.priority==="Baja"?"selected":""}>Baja</option></select></div></div>
 <section class="subpanel"><h3>Definition of Done</h3><div class="checklist">${dod.length?dod.map(x=>`<label class="check-row"><input type="checkbox" data-dod-id="${esc(x.id)}" ${x.is_completed?"checked":""}> <span>${esc(x.description)}</span></label>`).join(""):"<div class=empty-drop>No hay requisitos DoD.</div>"}</div><div class="inline-add"><input id="new-dod" placeholder="Nuevo requisito DoD"><button class="btn" id="add-dod">+ Agregar</button></div></section><section class="subpanel"><h3>Evidencia</h3>${ev.map(x=>`<div class="evidence-row"><span>${esc(x.type)}</span><a href="${esc(x.url_or_reference)}" target="_blank" rel="noopener">${esc(x.url_or_reference)}</a></div>`).join("")}<div class="inline-add"><input id="new-evidence" placeholder="URL o referencia"><button class="btn" id="add-evidence">+ Registrar</button></div></section><div class="modal-actions"><button class="btn" id="save-detail">Guardar cambios</button><button class="btn" id="start-task">Pasar a IN_PROGRESS</button><button class="btn primary" id="complete-task">Completar iniciativa</button><button class="btn danger-btn" id="cancel-task">Cancelar</button></div></section>
 <aside class="gate-panel"><h3>Gatekeeper</h3><div class="gate ${ready.allowed?"pass":"fail"}"><b>Definition of Ready</b><span>${ready.allowed?"✓ Lista para iniciar":"! Faltan requisitos"}</span></div><ul>${(ready.issues.length?ready.issues:["Nombre, descripción, pilar, objetivo, éxito, responsable, dependencias y DoD definidos."]).map(x=>`<li>${esc(x)}</li>`).join("")}</ul><div class="gate ${done.allowed?"pass":"fail"}"><b>Definition of Done</b><span>${done.allowed?"✓ Puede cerrarse":"! Pendiente"}</span></div><ul>${dod.length?dod.map(x=>`<li>${x.is_completed?"✓":"○"} ${esc(x.description)}</li>`).join(""):"<li>No hay checklist DoD.</li>"}</ul><div class="gate-meta">${ev.length} evidencia(s) registrada(s)</div></aside></div></div></div>`;
}
function bindModal(id){
 const q=s=>document.querySelector(s), close=()=>q("#initiative-modal")?.remove();q("#close-modal").onclick=close;
 q("#save-detail").onclick=()=>save(id);q("#add-dod")?.addEventListener("click",()=>addDod(id));q("#add-evidence")?.addEventListener("click",()=>addEvidence(id));q("#start-task").onclick=()=>start(id);q("#complete-task").onclick=()=>complete(id);q("#cancel-task").onclick=()=>cancel(id);document.querySelectorAll("[data-dod-id]").forEach(x=>x.addEventListener("change",()=>toggleDod(id,x.dataset.dodId,x.checked)));
}
async function toggleDod(taskId,itemId,checked){const d=state.get(),x=d.checklist.find(a=>a.id===itemId);if(!x)return;await db.put("checklist",{...x,is_completed:checked,completed_at:checked?new Date().toISOString():null});await log(taskId,checked?"DOD_COMPLETED":"DOD_REOPENED",x.description);state.set(await db.snapshot());openInitiativeDetail(taskId)}
async function addDod(taskId){const input=q("#new-dod"),description=input?.value.trim();if(!description)return toast("Escribe el requisito DoD.","error");await db.put("checklist",{id:crypto.randomUUID(),task_id:taskId,category:"DOD",description,required:true,is_completed:false});await log(taskId,"DOD_ADDED",description);state.set(await db.snapshot());openInitiativeDetail(taskId)}
async function addEvidence(taskId){const input=q("#new-evidence"),ref=input?.value.trim();if(!ref)return toast("Agrega una URL o referencia.","error");await db.put("evidence",{id:crypto.randomUUID(),task_id:taskId,type:ref.startsWith("http")?"URL":"REFERENCE",url_or_reference:ref,created_at:new Date().toISOString()});await log(taskId,"EVIDENCE_ADDED",ref);state.set(await db.snapshot());openInitiativeDetail(taskId)}
async function save(id){const d=state.get(),t=d.initiatives.find(x=>x.id===id);const u={...t,title:q("#f-title").value,description:q("#f-description").value,pillar:q("#f-pillar").value,owner:q("#f-owner").value,objective:q("#f-objective").value,success_criteria:q("#f-success").value,dependencies:q("#f-dependencies").value,priority:q("#f-priority").value,updated_at:new Date().toISOString()};
 await db.put("initiatives",u);await log(id,"INITIATIVE_UPDATED","Datos de iniciativa actualizados");state.set(await db.snapshot());closeAndRender();
}
async function start(id){const d=state.get(),t=d.initiatives.find(x=>x.id===id);const r=canStartTaskReady(t,d.checklist);if(!r.allowed)return toast(r.reason,"error");const w=validateStatusChange(t,"IN_PROGRESS",d.initiatives);if(!w.allowed)return toast(w.reason,"error");const u={...t,status:"IN_PROGRESS",started_at:t.started_at||new Date().toISOString(),updated_at:new Date().toISOString()};await db.put("initiatives",u);await log(id,"STATUS_CHANGED",`${t.status} → IN_PROGRESS`);state.set(await db.snapshot());closeAndRender();toast("Iniciativa iniciada: READY + WIP validados.","success")}
async function complete(id){const d=state.get(),t=d.initiatives.find(x=>x.id===id),r=canCompleteTask(t,d.checklist,d.evidence);if(!r.allowed)return toast(r.reason,"error");const u={...t,status:"DONE",completed_at:new Date().toISOString(),updated_at:new Date().toISOString()};await db.put("initiatives",u);await log(id,"STATUS_CHANGED",`${t.status} → DONE; WIP liberado automáticamente`);state.set(await db.snapshot());closeAndRender();toast("Iniciativa completada. WIP liberado.","success")}
async function cancel(id){const reason=prompt("Motivo de cancelación (obligatorio):");if(!reason?.trim())return toast("La cancelación requiere un motivo.","error");const d=state.get(),t=d.initiatives.find(x=>x.id===id),u={...t,status:"CANCELLED",cancellation_reason:reason.trim(),updated_at:new Date().toISOString()};await db.put("initiatives",u);await log(id,"CANCELLED",reason.trim());state.set(await db.snapshot());closeAndRender();toast("Iniciativa cancelada y WIP liberado.","success")}
async function log(entity_id,action,detail){await db.put("activity",{id:crypto.randomUUID(),timestamp:new Date().toISOString(),entity_id,action,detail})}
function closeAndRender(){document.querySelector("#initiative-modal")?.remove();window.dispatchEvent(new Event("rgt:render"))}
function q(s){return document.querySelector(s)}
function toast(message,type){let el=document.querySelector("#rgt-toast");if(!el){el=document.createElement("div");el.id="rgt-toast";document.body.appendChild(el)}el.className=`toast ${type}`;el.textContent=message;clearTimeout(window.__rgtToast);window.__rgtToast=setTimeout(()=>el.remove(),3500)}
